platform: x64

image:
- Visual Studio 2015

install:
- ps: Write-Output 'Install completed.'

build_script:
- powershell C:\projects\qaccelerator\build_qx.ps1 basic
- powershell C:\projects\qaccelerator\build_qx.ps1 installer
