platform: x64

#image:
#- Visual Studio 2017

install:
- ps: Write-Output 'Install completed.'

#build_script:
#- ps: Write-Output 'Buid completed.'
build_script:
- ps: Write-Output 'Build completed.'
